import dayjs from 'dayjs'

export const MatchList = [
  {
    homeName: 'Toronto Raptors',
    homeSlug: 'TOR',
    homeForm: ['W', 'W', 'L', 'W', 'L'],
    awayName: 'Detroit Pistons',
    awaySlug: 'DET',
    awayForm: ['L', 'W', 'L', 'L', 'L'],
    matchStart: dayjs().format('HH:mm A'),
  },
  {
    homeName: 'Indiana Pacers',
    homeSlug: 'IND',
    homeForm: ['L', 'L', 'L', 'L', 'W'],
    awayName: 'Atlanta Hawks',
    awaySlug: 'ATL',
    awayForm: ['W', 'W', 'W', 'W', 'W'],
    matchStart: dayjs().format('HH:mm A'),
  },
  {
    homeName: 'Cleveland Cavaliers',
    homeSlug: 'CLE',
    homeForm: ['L', 'L', 'L', 'L', 'L'],
    awayName: 'Brooklyn Nets',
    awaySlug: 'BKN',
    awayForm: ['W', 'W', 'L', 'W', 'W'],
    matchStart: dayjs().format('HH:mm A'),
  },
  {
    homeName: 'New Orlean Pelicans',
    homeSlug: 'NOP',
    homeForm: ['L', 'W', 'L', 'L', 'L'],
    awayName: 'Miami Heat',
    awaySlug: 'MIA',
    awayForm: ['L', 'W', 'W', 'W', 'L'],
    matchStart: dayjs().format('HH:mm A'),
  },
  {
    homeName: 'Washington Wizards',
    homeSlug: 'WAS',
    homeForm: ['L', 'W', 'L', 'L', 'W'],
    awayName: 'Charlotte Hornets',
    awaySlug: 'CHA',
    awayForm: ['W', 'W', 'L', 'L', 'L'],
    matchStart: dayjs().format('HH:mm A'),
  },
  {
    homeName: 'Orlando Magic',
    homeSlug: 'ORL',
    homeForm: ['L', 'L', 'L', 'L', 'L'],
    awayName: 'New York Knicks',
    awaySlug: 'NYK',
    awayForm: ['W', 'W', 'W', 'W', 'W'],
    matchStart: dayjs().format('HH:mm A'),
  },
  {
    homeName: 'Los Angles Lakers',
    homeSlug: 'LAL',
    homeForm: ['W', 'W', 'W', 'L', 'L'],
    awayName: 'Milawukee Bucks',
    awaySlug: 'MIL',
    awayForm: ['W', 'W', 'W', 'W', 'W'],
    matchStart: dayjs().format('HH:mm A'),
  },
]
